### ISSUE TITLE
Upgrading form 2.0.5->2.1.1 fails to load previous checkpoints

### ISSUE THREAD

**Issue by slyons** [hdinsight/spark-eventhubs#100]
When upgrading from release 2.0.5 to 2.1.1 I get the following exception:

`java.lang.IllegalStateException: detect corrupt progress tracking file at <time> <namespace> 0 <ehub> 9 2808934696544 9791652 it might be a bug in the implementation of underlying file system`

Is there a better way to transition?

This might be another case to support external tracking stores so that schema evolution can happen if necessary.

**Comment by CodingCat** [comment]
it is by design, 

you have to clean your progress file directory and then use filter parameter like eventhubs.filter.enqueueTime to catch up the processing
