### ISSUE TITLE
java.util.NoSuchElementException when using enqueueTime

### ISSUE THREAD

**Issue by slyons** [hdinsight/spark-eventhubs#101]
Some tasks are failing when using enqueueTime:

```
17/07/05 19:34:14 WARN TaskSetManager: Lost task 10.0 in stage 0.0 (TID 10, 10.0.0.9): java.util.NoSuchElementException
        at scala.collection.LinearSeqOptimized$class.last(LinearSeqOptimized.scala:148)
        at scala.collection.immutable.List.last(List.scala:84)
        at org.apache.spark.eventhubscommon.rdd.EventHubsRDD.compute(EventHubsRDD.scala:119)
```

Using driver version 2.1.1

**Comment by CodingCat** [comment]
would you please provide the log entries around this exception?

**Comment by slyons** [comment]
There isn't much beyond trying to read from the various partitions. No other logging is present.

**Comment by CodingCat** [comment]
the issue is tracked in https://github.com/hdinsight/spark-eventhubs/issues/103 (the description may not be absolutely accurate, as we did test with a "non-exist" timestamp before which turns out to be working)

We will resolve it before the next release

**Comment by CodingCat** [comment]
would you also provide the value you pass to this parameter?

**Comment by CodingCat** [comment]
and I still want to see the log around the exception, specifically, I need to check the line printed by https://github.com/hdinsight/spark-eventhubs/blob/master/core/src/main/scala/org/apache/spark/eventhubscommon/rdd/EventHubsRDD.scala#L106

**Comment by slyons** [comment]
The number was 1499040000, but there was no output from that line in the logs that I could see.

**Comment by CodingCat** [comment]
I didn't see it is possible to execute https://github.com/hdinsight/spark-eventhubs/blob/master/core/src/main/scala/org/apache/spark/eventhubscommon/rdd/EventHubsRDD.scala#L119 without printing any log

**Comment by CodingCat** [comment]
cannot reproduce
