### ISSUE TITLE
EventHubDirectDStream always waits once enter graph.wait()

### ISSUE THREAD

**Issue by Yifei891031** [hdinsight/spark-eventhubs#107]
In EventHubDirectDStream.scala,
in def compute() line 333
Once it enter this while loop, it just waits there, it will never executes the next line...

You can reproduce this by the following setting for direct stream:
batch duration = 5s,
window(Seconds(10), Seconds(5))

**Comment by CodingCat** [comment]
cannot repro, that line is trying to wait for your last batch to finish, please check if your batch ever finished

**Comment by CodingCat** [comment]
discussed offline
