### ISSUE TITLE
Spark with IOTHUB instead of EventHub

### ISSUE THREAD

**Issue by khajaasmath786** [hdinsight/spark-eventhubs#115]
HI,

I am looking into the docs where we can pull from Azure IOTHUB instead of EventHUB. is there a way we can do with this.

Properties I have are below and I cannot map them to eventhub as they are both different.

IotHub.EventHubCompatibleName=nstxxxxx
IotHub.EventHubCompatibleEndpoint=Endpoint=sb://iothub-XXXXXX-184065-7986533c4f.servicebus.windows.net/;SharedAccessKeyName=iothubowner;SharedAccessKey=YYYYYYYY
IotHub.AccessKeyName=service
IotHub.AccessKeyValue=CSjIIiqkzXXXXN+qYxxtaCSK/UYYYYYYmJv/3c=
IotHub.ConsumerGroup=_SparkWithkafka
IotHub.Partitions=32

This is not matching with values mentioned by library.
 "eventhubs.namespace" -> inputOptions(Symbol(EventhubsArgumentKeys.EventhubsNamespace)).asInstanceOf[String],
      "eventhubs.name" -> inputOptions(Symbol(EventhubsArgumentKeys.EventhubsName)).asInstanceOf[String],
      "eventhubs.policyname" -> inputOptions(Symbol(EventhubsArgumentKeys.PolicyName)).asInstanceOf[String],
      "eventhubs.policykey" -> inputOptions(Symbol(EventhubsArgumentKeys.PolicyKey)).asInstanceOf[String],
      "eventhubs.consumergroup" -> inputOptions(Symbol(EventhubsArgumentKeys.ConsumerGroup)).asInstanceOf[String],
      "eventhubs.partition.count" -> inputOptions(Symbol(EventhubsArgumentKeys.PartitionCount))
      .asInstanceOf[Int].toString,
      "eventhubs.checkpoint.interval" -> inputOptions(Symbol(EventhubsArgumentKeys.BatchIntervalInSeconds))
      .asInstanceOf[Int].toString,
      "eventhubs.checkpoint.dir" -> inputOptions(Symbol(EventhubsArgumentKeys.CheckpointDirectory)).asInstanceOf[String]

Thanks,
Asmath

**Comment by sabeegrewal** [comment]
Hey Asmath, 

When you create your ```eventhubParamters```, we need the **1)** EventHub name, **2)** EventHub Namespace name, **3)** Key name, and **4)** Key.  

Let's take these one at a time:
- Your EventHub name will be your ```IoTHub.EventHubCompatibleName```. 
- Your Namespace name will be a substring of your ```IotHub.EventHubCompatibleEndpoint``` - the part that reads ```iothub-XXXXXX-184065-7986533c4f``` is what you should use. 
- Your Key name is ```iothubowner``` (this is also a substring of your ```IotHub.EventHubCompatibleEndpoint```)
- Your Key is the part you put as ```YYYYYYYY``` (also in your endpoint!)

So, here's a quick sample of what this would look like:
```
val eventhubParameters = Map[String, String] (
      "eventhubs.policyname" -> "iothubowner",
      "eventhubs.policykey" -> "YYYYYYYY",
      "eventhubs.namespace" -> "iothub-XXXXXX-184065-7986533c4f",
      "eventhubs.name" -> IotHub.EventHubCompatibleName,
      "eventhubs.partition.count" -> "32",
      "eventhubs.consumergroup" -> "_SparkWithkafka"
    )
```

I'm fairly sure this is correct, but please let me know if this does/doesn't work!! Once we get it figured out, I'll get some documentation up in the repo. 

Thanks,
Sabee

**Comment by khajaasmath786** [comment]
Hi Sabee,

Thanks so much for your quick response.  We are big azure workshop now and we are trying to ingest this data into  hadoop .  I am still getting errors as below when trying to run the example. Could you please help me with correct parameters here. I am running below example

https://github.com/hdinsight/spark-streaming-data-persistence-examples/blob/master/src/main/scala/com/microsoft/spark/streaming/examples/workloads/EventhubsEventCount.scala


Here are my actual params from IOT hub.

IotHub.EventHubCompatibleEndpoint=Endpoint=sb://iothub-ns-xxxxxxx-yyyy-7986533c4f.servicebus.windows.net/;SharedAccessKeyName=iothubowner;SharedAccessKey=aaaaabbbbbcccccdddddd
IotHub.EventHubCompatibleName=nstsyyyyyyyyyyyyy
IotHub.AccessKeyName=service
IotHub.AccessKeyValue=ggggggghhhhhhhhhhyyyyyyyy
IotHub.ConsumerGroup=_nststeutoccihonpremkafka
IotHub.Partitions=32

Values that I passed as parmaters

--eventhubs-namespace iothub-ns-xxxxxxx-yyyy-7986533c4f
--eventhubs-name nstsyyyyyyyyyyyyy
--policy-name iothubowner
--policy-key aaaaabbbbbcccccdddddd
--consumer-group _ nststeutoccihonpremkafka
--partition-count 32
--batch-interval-in-seconds 10
--checkpoint-directory '/EventCheckpoint10'

Error When I ran the code:

17/08/03 20:58:11 WARN trace: UnHandled exception while processing events in reactor:
java.nio.channels.UnresolvedAddressException
org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:112)
org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:309)
org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:277)
com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:340)
java.lang.Thread.run(Thread.java:748)Cause: null
sun.nio.ch.Net.checkAddress(Net.java:101)
sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:622)
org.apache.qpid.proton.reactor.impl.IOHandler.handleBound(IOHandler.java:155)
org.apache.qpid.proton.reactor.impl.IOHandler.onUnhandled(IOHandler.java:372)
org.apache.qpid.proton.engine.BaseHandler.onConnectionBound(BaseHandler.java:58)
org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:131)
org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:309)
org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:277)
com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:340)
java.lang.Thread.run(Thread.java:748)


is there any fire wall issue? I was able to run and get the data into kafka with connector from github( https://github.com/Azure/toketi-kafka-connect-iothub ) with same properties. We want to try the spark streaming concept instead of going through kafka and again doing streaming. 

any suggestions would really help us. Thanks in advance

Regards,
Asmath

**Comment by khajaasmath786** [comment]
I was researching after posting this question, I ran the program https://stackoverflow.com/questions/40739664/error-creating-spark-streamingcontext-to-azure-iothub

Initially I got the same error. After a couple of retries, I can see the spark job running in UI but it is still waitinig to process the executors so I cannot confirm if it is really receiving messages. Will try in our cluster, currently I am running on my standalone spark in laptop. Will test with small data and confirm.

**Comment by khajaasmath786** [comment]
We are trying to open the port for azure from our inhouse cluster. what is port and protocol used by spark in this github example for connecting IOT hub.? 


MQTT | 8883
-- | --
MQTT over WebSockets | 443
AMQP | 5671
AMQP over WebSockets | 443
HTTP | 443


Thanks,
Asmath

**Comment by sabeegrewal** [comment]
The Spark-EventHubs connector uses the EventHub's Java client, and the Java client uses AMQP over port 5671 by default. Do you have that port open in your system?

**Comment by khajaasmath786** [comment]
Hi, Here is the exception that I getting when running in cluster. Spark UI shows below logs in executors. May  I know how to resolve it.

Job aborted due to stage failure: Failed to serialize task 289, not attempting to retry it. Exception during serialization: java.io.IOException: com.esotericsoftware.kryo.KryoException: java.lang.IllegalArgumentException: Unable to create serializer &quot;com.esotericsoftware.kryo.serializers.FieldSerializer&quot; for class: org.apache.spark.streaming.eventhubs.EventHubsClientWrapper +details
Job aborted due to stage failure: Failed to serialize task 289, not attempting to retry it. Exception during serialization: java.io.IOException: com.esotericsoftware.kryo.KryoException: java.lang.IllegalArgumentException: Unable to create serializer "com.esotericsoftware.kryo.serializers.FieldSerializer" for class: org.apache.spark.streaming.eventhubs.EventHubsClientWrapper
Serialization trace:
org$apache$spark$streaming$eventhubs$EventHubsReceiver$$receiverClient (org.apache.spark.streaming.eventhubs.EventHubsReceiver)

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.microsoft.spark.streaming.examples</groupId>
  <artifactId>spark-streaming-data-persistence-examples</artifactId>
  <version>2.0.0</version>
  <name>${project.artifactId}</name>
  <description>Spark Streaming With Event Hubs</description>
  <inceptionYear>2015</inceptionYear>

  <properties>
    <maven.compiler.source>1.7</maven.compiler.source>
    <maven.compiler.target>1.7</maven.compiler.target>
    <encoding>UTF-8</encoding>
    <scala.version>2.11.8</scala.version>
    <scala.compat.version>2.11.8</scala.compat.version>
    <scala.binary.version>2.11</scala.binary.version>
    <spark.version>2.0.0</spark.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.scala-lang</groupId>
      <artifactId>scala-library</artifactId>
      <version>${scala.version}</version>
      
    </dependency>
    <dependency>
      <groupId>org.apache.spark</groupId>
      <artifactId>spark-core_${scala.binary.version}</artifactId>
      <version>${spark.version}</version>
      
    </dependency>
    <dependency>
      <groupId>org.apache.spark</groupId>
      <artifactId>spark-streaming_${scala.binary.version}</artifactId>
      <version>${spark.version}</version>
      
    </dependency>
    <dependency>
      <groupId>org.apache.spark</groupId>
      <artifactId>spark-sql_${scala.binary.version}</artifactId>
      <version>${spark.version}</version>
      
    </dependency>
    
    <dependency>
      <groupId>edu.stanford.nlp</groupId>
      <artifactId>stanford-corenlp</artifactId>
      <version>3.8.0</version>
    </dependency>

    <dependency>
      <groupId>org.apache.spark</groupId>
      <artifactId>spark-hive_${scala.binary.version}</artifactId>
      <version>${spark.version}</version>
      
    </dependency>
    <dependency>
      <groupId>com.microsoft.azure</groupId>
      <artifactId>spark-streaming-eventhubs_2.11</artifactId>
      <version>2.0.2</version>
    </dependency>
    <dependency>
      <groupId>com.microsoft.azure.sdk.iot</groupId>
      <artifactId>iot-service-client</artifactId>
      <version>1.7.23</version>
    </dependency>
    <dependency>
      <groupId>com.microsoft.azure.sdk.iot</groupId>
      <artifactId>iot-device-client</artifactId>
      <version>1.3.30</version>
    </dependency>
    <dependency>
      <groupId>com.google.code.gson</groupId>
      <artifactId>gson</artifactId>
      <version>2.3.1</version>
    </dependency>
    
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-log4j12</artifactId>
      <version>1.7.6</version>

    </dependency>
    <dependency>
      <groupId>com.microsoft.azure</groupId>
      <artifactId>azure-eventhubs-eph</artifactId>
      <version>0.14.0</version>
    </dependency>
    
    <dependency>
      <groupId>ch.qos.logback</groupId>
      <artifactId>logback-classic</artifactId>
      <version>1.2.3</version>

    </dependency>


    <dependency>
      <groupId>com.microsoft.azure.iothub-java-client</groupId>
      <artifactId>iothub-java-service-client</artifactId>
      <version>1.0.7</version>
    </dependency>

    <dependency>
      <groupId>com.microsoft.azure</groupId>
      <artifactId>azure-eventhubs</artifactId>
      <version>0.13.0</version>
    </dependency>
    
<dependency>
    <groupId>com.esotericsoftware.kryo</groupId>
    <artifactId>kryo</artifactId>
    <version>2.16</version>
</dependency>
    

    
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.8.1</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.scalatest</groupId>
      <artifactId>scalatest</artifactId>
      <version>1.2</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <sourceDirectory>src/main/scala</sourceDirectory>
    <testSourceDirectory>src/test/scala</testSourceDirectory>
    <plugins>
      <plugin>
        <groupId>org.scala-tools</groupId>
        <artifactId>maven-scala-plugin</artifactId>
        <version>2.15.0</version>
        <executions>
          <execution>
            <goals>
              <goal>compile</goal>
              <goal>testCompile</goal>
            </goals>
            <configuration>
              <args>
                <arg>-dependencyfile</arg>
                <arg>${project.build.directory}/.scala_dependencies</arg>
              </args>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>2.6</version>
        <configuration>
          <useFile>false</useFile>
          <disableXmlReport>true</disableXmlReport>
          <includes>
            <include>**/*Test.*</include>
            <include>**/*Suite.*</include>
          </includes>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <version>2.4.1</version>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>shade</goal>
            </goals>
            <configuration>
              <filters>
                <filter>
                  <artifact>*:*</artifact>
                  <excludes>
                    <exclude>META-INF/*.SF</exclude>
                    <exclude>META-INF/*.DSA</exclude>
                    <exclude>META-INF/*.RSA</exclude>
                  </excludes>
                </filter>
              </filters>
              <artifactSet>
                <includes>
                  <include>com.microsoft.azure</include>
                </includes>
              </artifactSet>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-assembly-plugin</artifactId>
				<version>2.4.1</version>
				<configuration>
					
					<descriptorRefs>
						<descriptorRef>jar-with-dependencies</descriptorRef>
					</descriptorRefs>
					
					<archive>
					  <manifest>
						<mainClass>com.microsoft.spark.streaming.examples.workloads.TestIotHub</mainClass>
					  </manifest>
					</archive>

				</configuration>
				<executions>
				  <execution>
					<id>make-assembly</id>
                                        
					<phase>package</phase>
					<goals>
						<goal>single</goal>
					</goals>
				  </execution>
				</executions>
			</plugin>
    </plugins>
  </build>
</project>



JDK in cluster: 1.7
Spark: Running spark2 of cloudera

Thanks,
Asmath

**Comment by khajaasmath786** [comment]
Here is my POM for your reference

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.microsoft.spark.streaming.examples</groupId>
  <artifactId>spark-streaming-data-persistence-examples</artifactId>
  <version>2.0.0</version>
  <name>${project.artifactId}</name>
  <description>Spark Streaming With Event Hubs</description>
  <inceptionYear>2015</inceptionYear>

  <properties>
    <maven.compiler.source>1.7</maven.compiler.source>
    <maven.compiler.target>1.7</maven.compiler.target>
    <encoding>UTF-8</encoding>
    <scala.version>2.11.8</scala.version>
    <scala.compat.version>2.11.8</scala.compat.version>
    <scala.binary.version>2.11</scala.binary.version>
    <spark.version>2.0.0</spark.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.scala-lang</groupId>
      <artifactId>scala-library</artifactId>
      <version>${scala.version}</version>
      
    </dependency>
    <dependency>
      <groupId>org.apache.spark</groupId>
      <artifactId>spark-core_${scala.binary.version}</artifactId>
      <version>${spark.version}</version>
      
    </dependency>
    <dependency>
      <groupId>org.apache.spark</groupId>
      <artifactId>spark-streaming_${scala.binary.version}</artifactId>
      <version>${spark.version}</version>
      
    </dependency>
    <dependency>
      <groupId>org.apache.spark</groupId>
      <artifactId>spark-sql_${scala.binary.version}</artifactId>
      <version>${spark.version}</version>
      
    </dependency>
    
    <dependency>
      <groupId>edu.stanford.nlp</groupId>
      <artifactId>stanford-corenlp</artifactId>
      <version>3.8.0</version>
    </dependency>

    <dependency>
      <groupId>org.apache.spark</groupId>
      <artifactId>spark-hive_${scala.binary.version}</artifactId>
      <version>${spark.version}</version>
      
    </dependency>
    <dependency>
      <groupId>com.microsoft.azure</groupId>
      <artifactId>spark-streaming-eventhubs_2.11</artifactId>
      <version>2.0.2</version>
    </dependency>
    <dependency>
      <groupId>com.microsoft.azure.sdk.iot</groupId>
      <artifactId>iot-service-client</artifactId>
      <version>1.7.23</version>
    </dependency>
    <dependency>
      <groupId>com.microsoft.azure.sdk.iot</groupId>
      <artifactId>iot-device-client</artifactId>
      <version>1.3.30</version>
    </dependency>
    <dependency>
      <groupId>com.google.code.gson</groupId>
      <artifactId>gson</artifactId>
      <version>2.3.1</version>
    </dependency>
    
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-log4j12</artifactId>
      <version>1.7.6</version>

    </dependency>
    <dependency>
      <groupId>com.microsoft.azure</groupId>
      <artifactId>azure-eventhubs-eph</artifactId>
      <version>0.14.0</version>
    </dependency>
    
    <dependency>
      <groupId>ch.qos.logback</groupId>
      <artifactId>logback-classic</artifactId>
      <version>1.2.3</version>

    </dependency>


    <dependency>
      <groupId>com.microsoft.azure.iothub-java-client</groupId>
      <artifactId>iothub-java-service-client</artifactId>
      <version>1.0.7</version>
    </dependency>

    <dependency>
      <groupId>com.microsoft.azure</groupId>
      <artifactId>azure-eventhubs</artifactId>
      <version>0.13.0</version>
    </dependency>
    
<dependency>
    <groupId>com.esotericsoftware.kryo</groupId>
    <artifactId>kryo</artifactId>
    <version>2.16</version>
</dependency>
    

    
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.8.1</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.scalatest</groupId>
      <artifactId>scalatest</artifactId>
      <version>1.2</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <sourceDirectory>src/main/scala</sourceDirectory>
    <testSourceDirectory>src/test/scala</testSourceDirectory>
    <plugins>
      <plugin>
        <groupId>org.scala-tools</groupId>
        <artifactId>maven-scala-plugin</artifactId>
        <version>2.15.0</version>
        <executions>
          <execution>
            <goals>
              <goal>compile</goal>
              <goal>testCompile</goal>
            </goals>
            <configuration>
              <args>
                <arg>-dependencyfile</arg>
                <arg>${project.build.directory}/.scala_dependencies</arg>
              </args>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>2.6</version>
        <configuration>
          <useFile>false</useFile>
          <disableXmlReport>true</disableXmlReport>
          <includes>
            <include>**/*Test.*</include>
            <include>**/*Suite.*</include>
          </includes>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <version>2.4.1</version>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>shade</goal>
            </goals>
            <configuration>
              <filters>
                <filter>
                  <artifact>*:*</artifact>
                  <excludes>
                    <exclude>META-INF/*.SF</exclude>
                    <exclude>META-INF/*.DSA</exclude>
                    <exclude>META-INF/*.RSA</exclude>
                  </excludes>
                </filter>
              </filters>
              <artifactSet>
                <includes>
                  <include>com.microsoft.azure</include>
                </includes>
              </artifactSet>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-assembly-plugin</artifactId>
				<version>2.4.1</version>
				<configuration>
					
					<descriptorRefs>
						<descriptorRef>jar-with-dependencies</descriptorRef>
					</descriptorRefs>
					
					<archive>
					  <manifest>
						<mainClass>com.microsoft.spark.streaming.examples.workloads.TestIotHub</mainClass>
					  </manifest>
					</archive>

				</configuration>
				<executions>
				  <execution>
					<id>make-assembly</id>
                                        
					<phase>package</phase>
					<goals>
						<goal>single</goal>
					</goals>
				  </execution>
				</executions>
			</plugin>
    </plugins>
  </build>
</project>

**Comment by sabeegrewal** [comment]
Could you share your code as well? I'd like to see how you set up the connector and how you create a DStream.

**Comment by khajaasmath786** [comment]
package com.microsoft.spark.streaming.examples.workloads


import com.microsoft.spark.streaming.examples.arguments.EventhubsArgumentParser.ArgumentMap
import com.microsoft.spark.streaming.examples.arguments.{EventhubsArgumentKeys, EventhubsArgumentParser}
import com.microsoft.spark.streaming.examples.common.StreamStatistics
import org.apache.spark._
import org.apache.spark.sql.SparkSession
import org.apache.spark.streaming.eventhubs.EventHubsUtils
import org.apache.spark.streaming.{Seconds, StreamingContext}
object TestIotHub{// extends BaseDriver{
  private val logger = org.apache.log4j.Logger.getLogger(this.getClass)
  def main (args: Array[String]) {

    val master=if(args.length>0) "local[*]" else "yarn"

    val eventhubsParams = Map[String, String] (
      "eventhubs.namespace" -> "iothub-ns-1112222333-7986533c4f",
      "eventhubs.name" -> "nWWWWWWWWWWWh",
      "eventhubs.policyname" -> "iothubowner",
      "eventhubs.policykey" -> "XXXXXXXXXXXXXXXXXXXXXXX",
      "eventhubs.consumergroup" -> "_YYYYYYYYYYYYYYYYYY",
      "eventhubs.partition.count" -> "32",
      "eventhubs.checkpoint.dir" -> "./EventCheckpoint44",
      "eventhubs.checkpoint.interval" -> "1000"
    )

    println("hai..............."+master)
    val sparkConf = new SparkConf().setMaster(master).setAppName("IoT Test")
   // .set("spark.serializer", "org.apache.spark.serializer.KryoSerializer")
    
    val ssc =  new StreamingContext(sparkConf, Seconds(1500))
    println("...............")

    val stream = EventHubsUtils.createUnionStream(ssc, eventhubsParams)
    //stream.
    println("..............."+stream.count())
    stream.foreachRDD((rdd, time) => {
      println("............."+rdd.first())
      logger.error(s"...............................................Collecting Data ${rdd.first()}")
     /* //if (rdd.count() > 0) {
      if (rdd.count() > 0) {
        println(f"Recieved ${rdd.count()} messages.")
      } else {
        println("No messages recieved.")
      }*/

    }
    )

    ssc.start()
    ssc.awaitTermination()

  }


}

**Comment by khajaasmath786** [comment]
I even tried EventHubCount with below parameters and got same error.

spark2-submit --class com.microsoft.spark.streaming.examples.workloads.EventhubsEventCount --master yarn  spark-streaming-data-persistence-examples-2.0.0-jar-with-dependencies.jar --eventhubs-namespace 'iothub-nsxxxx-7986533c4f' --eventhubs-name 'xxxx' --policy-name '[iothubowner]' --policy-key '[pReDlJBLzemSPN5pZxmDQcxc5vExxxxxxX3XeJvE=]' --consumer-group '_nststexxxxxpremkafka' --partition-count  32 --batch-interval-in-seconds 10 --checkpoint-directory '/EventCheckpoint10' --event-count-folder '/EventCount/EventCount10' --job-timeout-in-minutes -1


Exception in thread "main" java.lang.UnsupportedClassVersionError: com/microsoft/azure/eventhubs/EventData : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at org.apache.spark.streaming.eventhubs.EventHubsUtils$.initializeSparkStreamingConfigurations(EventHubsUtils.scala:37)
        at com.microsoft.spark.streaming.examples.workloads.EventhubsEventCount$.createStreamingContext(EventhubsEventCount.scala:60)
        at com.microsoft.spark.streaming.examples.workloads.EventhubsEventCount$$anonfun$2.apply(EventhubsEventCount.scala:117)
        at com.microsoft.spark.streaming.examples.workloads.EventhubsEventCount$$anonfun$2.apply(EventhubsEventCount.scala:117)
        at scala.Option.getOrElse(Option.scala:121)
        at org.apache.spark.streaming.StreamingContext$.getOrCreate(StreamingContext.scala:826)
        at com.microsoft.spark.streaming.examples.workloads.EventhubsEventCount$.main(EventhubsEventCount.scala:116)
        at com.microsoft.spark.streaming.examples.workloads.EventhubsEventCount.main(EventhubsEventCount.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:736)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:185)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:210)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:124)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

can you confirm if I also passed parameters correctly , passing string with ' and []  as per the usage syntax.

**Comment by khajaasmath786** [comment]
After little more reasearch, i found this link.

https://github.com/Azure/azure-event-hubs-java

where it says the java jdk version needs to be 1.8 or higher. can this be run with jdk 1.7 from cluster?

**Comment by sabeegrewal** [comment]
Yea, so that's what I wanted to see. You need to upgrade to Java 8, and I'd recommend using Direct Streams as well. Check out the Build Prerequisites in the README to make sure you have the correct versions for everything else too.

**Comment by khajaasmath786** [comment]
Thanks Sabeegrewal for your answers. I have one last  question. Unfortunately I am not able to confirm if this code is working as I cannot test in cluster due to JDK dependency.

However, I tested the same in my laptop by having spark installed on my windows laptop. I can see the sparkUI showing 32(--partition-count 32) active jobs when I ran this job. does it mean the connection is successful and will work if I have enough resources/memory?

**Comment by sabeegrewal** [comment]
The Spark UI should tell you how many batches have been processed as well. Is that number non-zero? Also, in your code, you print out the stream count. Is that value non-zero? If you can see batches successfully completing OR a non-zero ```stream.count()```, you're in business.

**Comment by khajaasmath786** [comment]
![image](https://user-images.githubusercontent.com/8755249/29048049-55d8b064-7b94-11e7-9f03-21934aac5ad5.png)

This is how my sparkUI looks after reducing partitioncount to 1. There is no input read in shuffle and input phase.

**Comment by khajaasmath786** [comment]
![image](https://user-images.githubusercontent.com/8755249/29078308-952d97c6-7c1f-11e7-8f98-9cfdde0e6fcc.png)

This is how my output operation looks. I am still not able to confirm if the connection was successful as I am not able to see the print message on console

**Comment by sabeegrewal** [comment]
Do you mind switching to direct streams? A test application would look like this:

```scala
    val progressDir = "xxxxxxx"
    val sourcePolicyName = "xxxxxxxxxxx"
    val sourcePolicykey = "xxxxxxxxxxxxxxxx"
    val sourceEventHubNamespace = "xxxxxxxxxxxxxx"
    val sourceEventHubName = "xxxxxxxxxxxxxxx"
    val batchDuration = 10

    val eventhubParameters = Map[String, String] (
      "eventhubs.policyname" -> sourcePolicyName,
      "eventhubs.policykey" -> sourcePolicykey,
      "eventhubs.namespace" -> sourceEventHubNamespace,
      "eventhubs.name" -> sourceEventHubName,
      "eventhubs.partition.count" -> "32",
      "eventhubs.consumergroup" -> "xxxxxxxxxxxxxxxx"
    )

    val conf = new SparkConf().setAppName("SparkEventHubsSample")
    val ssc = new StreamingContext(conf, Seconds(batchDuration))

    val eventHubsStream = EventHubsUtils
      .createDirectStreams(ssc, sourceEventHubNamespace, progressDir, Map(sourceEventHubName -> eventhubParameters))

    eventHubsStream.count().print()

    ssc.start()
    ssc.awaitTermination()
```

You'd need to set master somewhere in this code OR do it when you submit the job.

**Comment by khajaasmath786** [comment]
Looks like this solution worked. I can see the input records in spark UI. here it is.

![image](https://user-images.githubusercontent.com/8755249/29099987-3ff5e016-7c6e-11e7-9a63-7122fe4b16ed.png)

**Comment by sabeegrewal** [comment]
Great! I'm glad we got this taken care of. I'll put up some documentation on connecting IoTHub to spark so it's easier for everyone in the future.

**Comment by khajaasmath786** [comment]
Hi Sabeegrawal,

I have opened the ticket once again. could you please provide your
suggestions.

https://github.com/Azure/spark-eventhubs/issues/130#issuecomment-325399072

Thanks,
Asmath
