### ISSUE TITLE
More readable identifier id warning for Eventhubs recriver

### ISSUE THREAD

**Issue by Myasuka** [hdinsight/spark-eventhubs#118]
To upgrade `azure-event-hubs-java` version to `0.14.3`, code set identifier id in [commit-109](https://github.com/hdinsight/spark-eventhubs/commit/e9babda4a077d81160280ad37793f46bb93c9bfb) as format: `$consumerGroup-$eventHubsName-$partitionId-$currentOffset`

However, this will cause receiver failure due to validation in [azure-event-hubs code](https://github.com/Azure/azure-event-hubs-java/blob/0.14.3/azure-eventhubs/src/main/java/com/microsoft/azure/eventhubs/ReceiverOptions.java#L73), which will throw exception like "receiverIdentifier length cannot exceed 64". Actually, this exception message is not so readable, and users might need some time to find the root cause, I think it's better to throw exception in Spark-eventhubs' [EventHubsClientWrapper.java](https://github.com/hdinsight/spark-eventhubs/blob/master/core/src/main/scala/org/apache/spark/eventhubscommon/client/EventHubsClientWrapper.scala#L152) file to tell users to shorten `consumerGroup` or `eventHubsName` names.

**Comment by CodingCat** [comment]
@sabeegrewal would you please work with Sreeram on this?

64 is too small for a distinguishable receiver ID, since in Spark app, we have to use offset/seq ID to distinguish receivers in different batches
