### ISSUE TITLE
Application fails to submit o HDInsight via IntelliJ

### ISSUE THREAD

**Issue by mrobson1975** [hdinsight/spark-eventhubs#122]
Hi, I'm trying to deploy the sample code provide for the Spark Structured Streaming example.  I've tried to submit the job via spark-submit on an HDInsight Cluster (running Spark 2.0) and via IntelliJ with the following exception:

User class threw exception: java.lang.ClassNotFoundException: Failed to find data source: eventhubs. Please find packages at https://cwiki.apache.org/confluence/display/SPARK/Third+Party+Projects

Could you provide some guidance to troubleshoot?

**Comment by sabeegrewal** [comment]
Hey mrobson1975, could you share the way you invoke ```spark-submit```?

**Comment by sabeegrewal** [comment]
Hey mrobson1975, I'm going to close this issue. If you're still having issues, please share how you're invoking ```spark-submit```. We can start troubleshooting from there!
