### ISSUE TITLE
Azure EventHubs classes conflicting with ServiceBus classes

### ISSUE THREAD

**Issue by romitgirdhar** [hdinsight/spark-eventhubs#128]
When trying to use this JAR along with the Azure Service Bus SDK, I get an error saying "**Exception in thread "main" java.lang.SecurityException: class "com.microsoft.azure.servicebus.ConnectionStringBuilder"'s signer information does not match signer information of other classes in the same package**".

This is caused by a signature mismatch since the "ConnectionStringBuilder" class is found in both, the spark-streaming-eventhubs jar and the servicebus jar. A temporary workaround is to shade the classes, but, it is extra debugging/dev effort required on the developer's part.

**Comment by CodingCat** [comment]
The root cause is in two sides

1. Due to some customer scenario in HDI, we had to include EventHubs in the released jar

2. EventHubs copied and pasted service bus source files in their release, so those files belonging to service bus sdks are included

**Comment by CodingCat** [comment]
that means, even we refer to eventhubs client through a maven pointer, you will still see this issue because of the fact that they copy and paste the files, so, please file an issue in their repo

**Comment by romitgirdhar** [comment]
Yes, that is correct. The corresponding Service Bus issue is here: https://github.com/Azure/azure-service-bus-java/issues/34 & EvenHubs issue is here: https://github.com/Azure/azure-event-hubs-java/issues/95

If this issue is resolved on the EventHubs and the ServiceBus side, there needs to be an updated version of the spark-eventhubs JAR pointing to the latest version of the event-hubs sdk.

**Comment by CodingCat** [comment]
yes, there are several undergoing features here, so this problem should be fixed in the next release once we update the dependency to 0.15
