### ISSUE TITLE
structured stream always reads all data

### ISSUE THREAD

**Issue by liupeirong** [hdinsight/spark-eventhubs#131]
In structured streaming, even when eventhubs.progressTrackingDir is specified and its content seems to be updated as each streaming job runs, when restarting a job, it always reads all the events in the eventhub.  Is there a way to read from the last checkpoint?

**Comment by CodingCat** [comment]
it's hard to identify the issue without any info from yarn log, etc.

if you're a user of HDI, I suggest you filing a support case

**Comment by CodingCat** [comment]
the user is running 2.2 which has inconsistent behavior than 2.1, and we will support it soon
