### ISSUE TITLE
Running EventHubsStructuredStreamingExample in cluster: cannot find data source "eventhubs"

### ISSUE THREAD

**Issue by p2bauer** [hdinsight/spark-eventhubs#139]
When submitting a simple job with just the sample code included, I seem to always get the following error on runtime when `val inputStream = sparkSession.readStream.format("eventhubs").options(eventhubParameters).load()` executes:

`java.lang.ClassNotFoundException: Failed to find data source: eventhubs. Please find packages at http://spark.apache.org/third-party-projects.html`

Any ideas on how to get the sample code `EventHubsStructuredStreamingExample` working?

**Comment by sabeegrewal** [comment]
Can you post the dependencies in your ```pom.xml```?

**Comment by p2bauer** [comment]
> <dependencies>
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-core_2.11</artifactId>
            <version>2.1.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-sql_2.11</artifactId>
            <version>2.1.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-streaming_2.11</artifactId>
            <version>2.1.0</version>
        </dependency>
        <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>spark-streaming-eventhubs_connector_2.11</artifactId>
            <version>2.1.2</version>
        </dependency>
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-mllib_2.11</artifactId>
            <version>2.1.0</version>
        </dependency>

**Comment by p2bauer** [comment]
The `spark-streaming-eventhubs_connector_2.11` portion I added after creating the project using the HDI IntelliJ template, since after some googling i thought that might help...

**Comment by sabeegrewal** [comment]
It needs to be like this:
```
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>spark-streaming-eventhubs_2.11</artifactId>
    <version>2.1.2</version>
</dependency>
```

So, instead of ```spark-streaming-eventhubs_connector_2.11```, you wanna do ```spark-streaming-eventhubs_2.11```. Let me know if that works!

**Comment by p2bauer** [comment]
@sabeegrewal that was absolutely it, works now.  thanks very much for your help. 👍
