### ISSUE TITLE
2 direct steams at the same time gives ERROR "detected lost partitions" 

### ISSUE THREAD

**Issue by navicore** [hdinsight/spark-eventhubs#47]
I have a driver program that consumes from eventhubs via 2.0.4-SNAPSHOT.

two different hubs in the same namespace with different policies via `EventHubsUtils.createDirectStreams` test good independently.

but when started in the same driver program with the same `ssc` give

```
[JobGenerator] ERROR o.a.s.s.e.EventHubDirectDStream - detected lost partitions List(camera-partition-0, camera-partition-1, camera-partition-2, camera-partition-3)
```

Which ever stream I start first will show up in the partition error.  If I comment out one, the other works fine.

Should multiple eventhubs be usable via a single `ssc`?

ps: building 2.0.4 for the new `isLocal` check on the progress_dir hdfs/adl enforcement and hoping to use wasbs.

**Comment by CodingCat** [comment]
can you provide the parameters you pass to createDirectDStreams?

**Comment by CodingCat** [comment]
basically, each DirectDStream can only map to a single namespace, if you have two eventhubs within the same namespace, you can only build a single EventHubsDirectDStream instance

**Comment by navicore** [comment]
Thanks @CodingCat.  I was able to process once I recreated my second eventhub in another namespace.
