### ISSUE TITLE
How to restrict the createunionstream.

### ISSUE THREAD

**Issue by ankushreddy** [hdinsight/spark-eventhubs#56]
Hi am trying to pull data from event hub.

we are  having 10 partitions in the eventhub. Am using createUnionStream to pull the events.
As am using createUnionStream to save as files. It is not writing into the file until a shutdownhook is called.
I need to stream the data or get the union of the streams for every 10 to 20 seconds instead of waiting for calling the shutdownhook.

Could you suggest if am missing anything or if we have that functionality implemented.

  package com.microsoft.spark.streaming.examples.workloads
  import org.apache.spark.streaming.{Seconds, StreamingContext}
  import org.apache.log4j.{Level, Logger}
  import org.apache.spark.streaming.eventhubs.EventHubsUtils
  import org.apache.spark.SparkContext
  import org.apache.spark.SparkConf
  import org.apache.spark.rdd.RDD
  import org.apache.spark._
  import org.apache.spark.sql.hive.HiveContext
  import java.util.concurrent.{ExecutorService, Executors}
  import com.microsoft.spark.streaming.examples.arguments.EventhubsArgumentKeys
  import com.microsoft.spark.streaming.examples.workloads.EventhubsToHiveTable.createStreamingContext
  import org.apache.spark.sql.SparkSession
  object HiveEventsTest2 {
    def b2s(a: Array[Byte]): String = new String(a)
    def createStreamingContext(): StreamingContext = {
	val ehParams = Map[String, String]( 
        "eventhubs.policyname" -> "Test_listen",
        "eventhubs.policykey" -> "<PloicyKey>",
        "eventhubs.namespace" -> "<Namespace>",
        "eventhubs.name" -> "<Name>",
        "eventhubs.partition.count" -> "10",
        "eventhubs.consumergroup" -> "$default",
        "eventhubs.checkpoint.dir" -> "/EventCheckpoint_0.1",
        "eventhubs.checkpoint.interval" -> "20"
      )
      val sparkConfiguration : SparkConf = EventHubsUtils.initializeSparkStreamingConfigurations
      sparkConfiguration.setAppName("Eventhubs Onerm")
      sparkConfiguration.set("spark.streaming.driver.writeAheadLog.allowBatching", "true")
      sparkConfiguration.set("spark.streaming.driver.writeAheadLog.batchingTimeout", "60000")
      sparkConfiguration.set("spark.streaming.receiver.writeAheadLog.enable", "true")
      sparkConfiguration.set("spark.streaming.driver.writeAheadLog.closeFileAfterWrite", "true")
      sparkConfiguration.set("spark.streaming.receiver.writeAheadLog.closeFileAfterWrite", "true")
      sparkConfiguration.set("spark.streaming.stopGracefullyOnShutdown", "true")
      val sparkSession : SparkSession = SparkSession.builder.config(sparkConfiguration).enableHiveSupport.getOrCreate
      val ssc = new StreamingContext(sparkSession.sparkContext, Seconds(5))
      ssc.checkpoint("/EventCheckpoint_0.1")
      var dataString :RDD[String] =sparkSession.sparkContext.emptyRDD
	val stream=EventHubsUtils.createUnionStream(ssc, ehParams)
      **//lines below are not getting executed until I stop the execution****
      stream.foreachRDD {
        rdd =>
            dataString=rdd.map(line=>b2s(line))            print("@@@@@@@@@@@@@@@@@@@@@@@@###########################################****************************************************************************#@$#$@############################@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")          print("@@@@@@@@@@@@@@@@@@@@@@@@###########################################****************************************************************************#@$#$@############################@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")
	    println("COUNT" +dataString.count())       print("@@@@@@@@@@@@@@@@@@@@@@@@###########################################****************************************************************************#@$#$@############################@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")      print("@@@@@@@@@@@@@@@@@@@@@@@@###########################################****************************************************************************#@$#$@############################@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")
            //dataString.saveAsTextFile("/EventCheckpoint_0.1/TextFile")     
      }
	ssc
    }
  def main(inputArguments: Array[String]): Unit = {
    val streamingContext = StreamingContext.getOrCreate("/EventCheckpoint_0.1",() => createStreamingContext())
    sys.ShutdownHookThread {
      println("Gracefully stopping Spark Streaming Application")
	println("*****************************************************########################################################################################################################")
      streamingContext.stop(true, true)
      println("Application stopped")
    }
  streamingContext.start()
  streamingContext.awaitTermination()
  }
}

If we see the code from this line //lines below are not getting executed until I stop the execution rest of the code is not getting executed until I stop the script.
Sorry for the confusion.

Thank You for your help.

Thanks,
Ankush Reddy

**Comment by CodingCat** [comment]
sorry, I didn't understand the question here, you do not want to save to file in a shutdown hook , but why you have 

```scala
sys.ShutdownHookThread {
println("Gracefully stopping Spark Streaming Application")
println("*****************************************************########################################################################################################################")
//val conf = new SparkConf().setAppName("Merging Files")
// val sc= new SparkContext(conf)
// sc.textFile("/EventCheckpoint_0.1/ParquetEvent/part*").coalesce(1).saveAsTextFile("/EventCheckpoint_0.1/SingleFile")
// sc.stop()
streamingContext.stop(true, true)
println("Application stopped")
}
```

**Comment by ankushreddy** [comment]
@CodingCat  Hi sorry for the confusion I have modified the code I mean removed all the comments.
If we look at println("COUNT" +dataString.count()) this is not getting executed until I press ctrl+c.

Thank You for your help.

**Comment by CodingCat** [comment]
how you detect this line is not executed? can you post a screenshot of your streaming UI?

**Comment by CodingCat** [comment]
and we also have other questions 

* how you start the application

* how many resources you allocate to the application

@arijitt

**Comment by ankushreddy** [comment]
Am printing a dummy line just to debug.
I started the application in local. yarn client and cluster mode.
in yarn client and cluster mode I have used 2 executors and 5 executor cores. driver memory as 2GB and executor memory as 2G.
As this is a streaming application.
Am expecting it should write the data in the batches for every 10 seconds.

**Comment by CodingCat** [comment]
wait...you have 10 partitions in eventhubs, and you only give 2 executors and 5 executor cores, that means you have 10 cores in total

because you are using receiver-based connection, these 10 cores would be used to run 10 receivers and no resources left for your data processing tasks. Once you killed the application, those receivers are killed and some pending data processing tasks are started (but quickly killed since the whole app is down)

Are you using Spark 2.0+? if yes, you can try direct dstream integration of Spark and Event Hubs which is much faster and resource-efficient

**Comment by ankushreddy** [comment]
Hi @CodingCat  when ever there is a single record in the stream it is taking forever to finish the process. and rest of the streaming process jobs are accumulating in queue.

Please find the screenshot and let me know if am missing anything.

![image](https://cloud.githubusercontent.com/assets/15848115/24721588/a065e030-19f5-11e7-90c5-3276e3f0ab2e.png)


Thanks You,
Ankush Reddy.

**Comment by CodingCat** [comment]
as I said, it is due to the fact that there is no resources left for your processing....you can either increase the number of cores or use direct dstream

**Comment by CodingCat** [comment]
update on this? otherwise I will close it

**Comment by ankushreddy** [comment]
I am using createDirectStream.

Could you please let me know if we have any documentation on the differences between union stream and direct stream.

Thanks,
Ankush.

**Comment by CodingCat** [comment]
We are uploading docs but still waiting for approval...basically it is the same high level idea of the diff beween kafka receiver based and direct dstream based integration

**Comment by CodingCat** [comment]
update on this? otherwise, I will close it

**Comment by ankushreddy** [comment]
@CodingCat  Thank You for your inputs Am closing this.
