### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by gordontyler** [hdinsight/spark-eventhubs#6]
This project should be published to Maven Central so that users do not get an unpleasant surprise when an older version is unexpectedly removed from the "private" repo.

**Comment by wmeints** [comment]
I just got a comment on issue #8 that confirms that this is pushed to maven central soon.
That should solve the problem with old versions becoming unavailable.

**Comment by arijitt** [comment]
Versions supported for Spark 1.6.2 and Spark 2.0.0 are now available in Maven Central. Follow the README in the corresponding branches.

**Comment by gordontyler** [comment]
Thanks!
