### ISSUE TITLE
Question Regarding CreateDirectStream.

### ISSUE THREAD

**Issue by ankushreddy** [hdinsight/spark-eventhubs#69]
Hi When I create a DirectStream Using CreateDirectStream.
Running the job with --num-executors 18 --executor-memory 512MB --conf spark.executor.cores=5

with below properties.
Am able to pull the data but the not at every 2 secs.
If am getting some 5000 records in a batch it is waiting for that 5000 records to process and start the next job. Mean while there are some 10,000 to 20,000 records getting stacked up and the next job is taking much longer time.
Is there any way I can increase the performance. or Optimize the job in such a way that it will do parallel processing.
Am unable to set the --conf spark.streaming.concurrentJobs=4 when pulling the data from event hub.

    val eventhubnamespace = "flightawarespark"
    val progressdir = "/Event/DirectStream/"
    val eventhubname_d = "flightaware"
    val ehParams = Map[String, String](
      "eventhubs.policyname" -> "Test_listen",
      "eventhubs.policykey" -> "PolicyKey",
      "eventhubs.namespace" -> "namespace",
      "eventhubs.name" -> "name",
      "eventhubs.partition.count" -> "10",
      "eventhubs.consumergroup" -> "$default",
      "eventhubs.checkpoint.dir" -> "/EventCheckpoint_0.1",
      "eventhubs.checkpoint.interval" -> "2"
    )
    println("testing spark")
    val conf = new SparkConf().set("spark.serializer", "org.apache.spark.serializer.KryoSerializer")//.setMaster("local[4]").setAppName("Eventhubs_Test")
    conf.registerKryoClasses(Array(classOf[PublishToTopic]))
    conf.set("spark.streaming.stopGracefullyOnShutdown", "true")
    val sc= new SparkContext(conf)
    val hiveContext = new HiveContext(sc)
    val sqlContext = new org.apache.spark.sql.SQLContext(sc)
    val pool:ExecutorService=Executors.newFixedThreadPool(10)
    val ssc = new StreamingContext(sc, Seconds(2))
    var dataString :RDD[String] =sc.emptyRDD
    val stream=EventHubsUtils.createDirectStreams(ssc,eventhubnamespace,progressdir,Map(eventhubname_d -> ehParams))

Thank you for your help.

Thanks,
Ankush Reddy.

**Comment by CodingCat** [comment]
1. you are setting 90 cores in your application, however, you need to be aware of that the maximum number of parallel tasks which can be started to fetch messages from your event hubs is equal to the number of partitions in your event hubs . 

2. You can increase parallelism by repartitioning after you get the messages (you need to ensure that the cost of repartitioning is less than the performance gain due to the increased parallelism

3. `spark.streaming.concurrentJobs` are not allowed here and in most of streaming applications (this will break the time sequence of your processing and hard to reason about what is happening)

4. you need to tune the batch interval to ensure that the processing latency is not longer (at least not much longer) than your interval

**Comment by ankushreddy** [comment]
Hi @CodingCat  am actually using repartitioning in my program I will try to set the partition to 32 and takeout repartition and see if there is any performance improvements.

Thanks,
Ankush Reddy.

**Comment by ankushreddy** [comment]
Hi @CodingCat.
When am creating a new eventhub in the same namespace. with more number of partitions am getting an error saying that EventHubDirectDstream: detected lost partitions List(evenhubname-partition-0, ....)

when I create a eventhub in new namespace then am getting an error saying that.
eventhub.java.lang.illegalargumentexception: requirement failed: progress file cannot be empty.


Thank you for your help.

**Comment by CodingCat** [comment]
Remove your checkpoint directory and progress file directory when you add more eventhubs...we do not support dynamically changing eventhubs number

**Comment by ankushreddy** [comment]
@CodingCat  Even after Increasing the partitions to 30 I don't see any difference in the Processing time. If my job is running for about 10 hours the number of records to process in each batch is increasing dynamically as it is taking more time to process.

**Comment by CodingCat** [comment]
@ankushreddy are you a HDInsight customer? if yes, let's setup a call

**Comment by ankushreddy** [comment]
@CodingCat Yes we are using HDInsight cluster.
Let me know how to what time we can have a call?

**Comment by CodingCat** [comment]
@ankushreddy can you ask CSS guy from MS you work with to send me email to schedule the meeting?
