### ISSUE TITLE
Scala 2.11 version

### ISSUE THREAD

**Issue by wmeints** [hdinsight/spark-eventhubs#8]
Hi, I'm planning on using this software in a Spark 2.0 project that is based on Scala 2.11.
Sadly the project currently doesn't have a 2.11 version. Would it be possible to build a 2.11 version also?

**Comment by arijitt** [comment]
Yes we will publish Spark Eventhubs receiver for Scala version 2.11 that will work with Spark 2.0. The version is under testing right now and we will push it early next week. From now on Spark Eventhubs receiver will be available in Maven Central. I will let you know the Maven coordinates in this thread and we will also have official documentation published.

**Comment by wmeints** [comment]
Yay, new version works. Thanks for updating the lib!
