### ISSUE TITLE
EventHubsUtils.createDirectStreams cant use azure china event hub endpoint

### ISSUE THREAD

**Issue by chenrui1988** [hdinsight/spark-eventhubs#91]
There's no parameter for EventHubsUtils.createDirectStreams  to specify azure china event hub endpoint, I see you are use “servicebus.windows.net”  in the code of RestfulEventHubClient classs ,  so we cant use this in china azure.

please add a parameter for setting event hub endpoint ！

**Comment by CodingCat** [comment]
will confirm with Event Hubs team to check if there is any other URL schema change for Azure@China...and RestfulClient will be replaced in the next release (not URL issue would be involved in that)
