### ISSUE TITLE
eventhubs.filter.enqueuetime documentation has incorrect unit

### ISSUE THREAD

**Issue by perthcha** [hdinsight/spark-eventhubs#96]
Based on what I am seeing in my program's behavior, it looks like the unit for eventhubs.filter.enqueuetime should be **seconds**, not **milliseconds**.

The docs are in these two files:

`"eventhubs.filter.enqueuetime": Unix time, millisecond since epoch, default to "0"`

https://github.com/hdinsight/spark-eventhubs/blob/ee7dcfe65843d624064308ce1da5be86cfdd3fa6/core/src/main/scala/org/apache/spark/eventhubscommon/Implicits.scala

https://github.com/hdinsight/spark-eventhubs/blob/170a90c562eb932c2a7afaa969fdbccd194f082a/core/src/main/scala/org/apache/spark/streaming/eventhubs/EventHubsUtils.scala

**Comment by CodingCat** [comment]
thanks for pointing out this...that's a mistake we made...will fix
