### ISSUE TITLE
Allow wasbs:// as prefix 

### ISSUE THREAD

**Issue by perthcha** [hdinsight/spark-eventhubs#98]
The code here prevents me from using Azure Blob storage (which is HDFS compatible).

https://github.com/hdinsight/spark-eventhubs/blob/94ca980ce3d777a44e247458ebc4a76ca1948012/core/src/main/scala/org/apache/spark/streaming/eventhubs/checkpoint/DfsBasedOffsetStore.scala

Please allow wasbs:// as a prefix as well

**Comment by CodingCat** [comment]
in receiver based stream, we will use the same directory for both offset store and spark streaming checkpoint/WAL. Unfortunately, the lack of support to append operation makes WASB unfit for the later case.

So, we will not support WASB until it makes append operation usable
